//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobitelShop_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mobiteli
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mobiteli()
        {
            this.NarudzbaStavke = new HashSet<NarudzbaStavke>();
        }
    
        public int Id { get; set; }
        public string Naziv { get; set; }
        public float Cijena { get; set; }
        public bool Status { get; set; }
        public int MemorijaId { get; set; }
        public int CpuJezgreId { get; set; }
        public int BrendoviId { get; set; }
        public string SlikaUrl { get; set; }
        public int OperativniSistemId { get; set; }
    
        public virtual Brendovi Brendovi { get; set; }
        public virtual CpuJezgre CpuJezgre { get; set; }
        public virtual Memorija Memorija { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NarudzbaStavke> NarudzbaStavke { get; set; }
        public virtual OperativniSistem OperativniSistem { get; set; }
    }
}
