//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobitelShop_API.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class hci231_MobitelShopEntities : DbContext
    {
        public hci231_MobitelShopEntities()
            : base("name=hci231_MobitelShopEntities")
        {
            Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Brendovi> Brendovi { get; set; }
        public virtual DbSet<CpuJezgre> CpuJezgre { get; set; }
        public virtual DbSet<Kupci> Kupci { get; set; }
        public virtual DbSet<Memorija> Memorija { get; set; }
        public virtual DbSet<Mobiteli> Mobiteli { get; set; }
        public virtual DbSet<NarudzbaStavke> NarudzbaStavke { get; set; }
        public virtual DbSet<Narudzbe> Narudzbe { get; set; }
        public virtual DbSet<OperativniSistem> OperativniSistem { get; set; }
        public virtual DbSet<StatusNarudzbe> StatusNarudzbe { get; set; }
        public virtual DbSet<Uloge> Uloge { get; set; }
        public virtual DbSet<Uposlenici> Uposlenici { get; set; }
    
        public virtual ObjectResult<Mobiteli> ms_SelectMobitelByNaziv(string naziv)
        {
            var nazivParameter = naziv != null ?
                new ObjectParameter("Naziv", naziv) :
                new ObjectParameter("Naziv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Mobiteli>("ms_SelectMobitelByNaziv", nazivParameter);
        }
    
        public virtual ObjectResult<Mobiteli> ms_SelectMobitelByNaziv(string naziv, MergeOption mergeOption)
        {
            var nazivParameter = naziv != null ?
                new ObjectParameter("Naziv", naziv) :
                new ObjectParameter("Naziv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Mobiteli>("ms_SelectMobitelByNaziv", mergeOption, nazivParameter);
        }
    
        public virtual ObjectResult<ms_SelectNarudzbaStavkeByKupacId_Result> ms_SelectNarudzbaStavkeByKupacId(Nullable<int> kupacId)
        {
            var kupacIdParameter = kupacId.HasValue ?
                new ObjectParameter("KupacId", kupacId) :
                new ObjectParameter("KupacId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ms_SelectNarudzbaStavkeByKupacId_Result>("ms_SelectNarudzbaStavkeByKupacId", kupacIdParameter);
        }
    }
}
