//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobitelShop_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NarudzbaStavke
    {
        public int Id { get; set; }
        public int Kolicina { get; set; }
        public float Cijena { get; set; }
        public float Iznos { get; set; }
        public int MobiteliId { get; set; }
        public int NarudzbaId { get; set; }
    
        public virtual Mobiteli Mobiteli { get; set; }
        public virtual Narudzbe Narudzbe { get; set; }
    }
}
